
name: Build

on:
  release:
    types:
      - published

jobs:
  buildlinux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8"
      - run: pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython
      - run: pip install -r pip-requirements.txt
      - run: pyinstaller build.spec
      - name: upload ubuntu artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/EasyChartGenerator
          asset_name: EasyChartGenerator_Ubuntu_bionic
          asset_content_type: application/exe
